### ISSUE TITLE
Improvement - `publish` button should be disable when the version is not saved.

### ISSUE THREAD

**Issue by lilyjazz** [pingcap/LinguFlow#38]
When I was editing a version and hadn't saved yet, I clicked the publish button, and it took effect. 

This behavior is risky because the unsaved state is an intermediate state. 

If clicked by accident, publishing an unintended version could potentially cause production incidents.

**Comment by shhdgit** [comment]
The publish action is version-specific. Unsaved changes have no version and will not be published.

**Comment by lilyjazz** [comment]
> The publish action is version-specific. Unsaved changes have no version and will not be published.

Yes, but I might start editing from a non-production version, which could mistakenly publish the non-production version.

**Comment by shhdgit** [comment]
get it. LGTM.

**Comment by lilyjazz** [comment]
When the builder contains unsaved content, the publish button should be disabled.
